### ISSUE TITLE
Incorrect XML comment in FluentClientExtensions.WithOptions and FluentClientExtensions.SetOptions

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#103]
The XML comments for the two arguments have been reversed:
- the comment for `ignoreHttpErrors` says `Whether to ignore null arguments when the request is dispatched` 
- the comment for `ignoreNullArguments` says `Whether HTTP error responses like HTTP 404 should be ignored; else raised as exceptions`.

**Comment by Pathoschild** [comment]
Thanks! Fixed via #104 for the upcoming FluentHttpClient 4.1.1.
