### ISSUE TITLE
RequestCoordinator is not on the IClient interface. Is that intentional?

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#115]
Is there a reason the `RequestCoordinator` property is only on the `FluentClient` class and not on the underlying `IClient` interface?

I'm asking because I noticed all the other properties (i.e.: `BaseClient`, `Formatters` and `Filters`) are on the interface and the request coordinator is the only one that's absent from the interface. I thought that was a little odd, but maybe I'm missing something????

**Comment by Jericho** [comment]
I could be wrong, but my guess is that this was a mixup and the intent was to treat this property no different than all other properties. 

Submitting a PR to add this property to the interface.

**Comment by Pathoschild** [comment]
Added via #116 for the upcoming FluentHttpClient 4.3.0. Thanks!
