### ISSUE TITLE
Can I use this repo to download multiple http files or string in parallel?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Pathoschild/FluentHttpClient#117]
I am writing to inquire about the suitability of your GitHub repository for a specific use case.

I am interested in using your repository to download multiple small files concurrently. The files I need to download are relatively small, ranging from 2KB to 5.6KB. I anticipate having up to 50 URLs, though typically no more than 15. The frequency of downloads varies throughout the day, with some periods having only 1 or 2 URLs, and occasionally none at all.

The URLs resemble the following examples:
http://worldtimeapi.org/Europe/London
http://worldtimeapi.org/Europe/Berlin ......

What I am trying to do is to send a group of http requests to different URLs, but the base URLs are the same, just like http://worldtimeapi.org/Europe/; but the last part of the URLs are different, like: London; Berlin.
I want to send all http requests and get responses in parallel, and process all responses within a short time, less than 1 second. So I need some multiple http download solutions.  But my task in not like Free Download Manager, which will download a big file with chunks.  Since all the files or json string from each URL is rather small, less than 5.6KB, so better to download each one in only one shot.
But the solution has to fix the http client for concurrency management, and other related issues.
These URLs represent endpoints that provide JSON data, and I need to download them quickly and efficiently, I also have to use Newtonsoft.json to parse the json format string get the necessary information. I plan to implement this functionality in C# using .NET 8.0 and Visual Studio 2022 on Windows 10.

Could you kindly confirm if your repository supports this use case? Additionally, if it does, I would greatly appreciate some general instructions on how to effectively leverage your repository for this purpose.

Thank you for your time and assistance. I look forward to your guidance.

**Comment by Pathoschild** [comment]
Yep, FluentHttpClient should work fine for that. It's a wrapper around [.NET's `HttpClient`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) which is threadsafe, supports unlimited concurrency, and has built-in optimizations like connection pooling. You can also optionally set the max concurrent requests per server to avoid overloading the target server (default unlimited). See the [`HttpClient` docs](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) for more info.

Concurrent usage is just like [the examples in the readme](https://github.com/Pathoschild/FluentHttpClient#readme); but make sure you create one client instance, reuse it for each concurrent request (so they can use the connection pooling and rate limiting), and dispose it when you're done. You can have an async method to fetch and parse the data using the client, then use `Task.WaitAll` or the [Task Parallel Library](https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl) to run it concurrently for each endpoint.

Feel free to ask if anything is unclear!

**Comment by zydjohnHotmail** [comment]
Hi, 
Thanks for your quick reply, since I am new to your repo.  And I want to use C# .net 8.0 target on .net 8.0; with Visual Studio 2022, and help from AI, I wrote the following code in one WinForms App project: using FluentlyHttpClient;
using Newtonsoft.Json.Linq;

namespace HttpRequestFluentlyForm
{
    public partial class Form1 : Form
    {
        public static async Task Request_Many_Urls()
        {
            IFluentHttpClientFactory clientFactory = new FluentHttpClientFactory(null);

            // Create a new FluentHttpClient
            IFluentHttpClient client = clientFactory.CreateBuilder("myClient")
                .WithBaseUrl("http://worldtimeapi.org/Europe/")
                .Build();

            // List of endpoints
            string[] endpoints = new string[] { "London", "Berlin", /* add more endpoints here */ };

            // Send requests to all endpoints concurrently
            Task<(FluentHttpResponse response, JObject json)>[] tasks = endpoints.Select(async endpoint =>
            {
                // Create a new request
                FluentHttpRequest request = client.CreateRequest()
                    .WithPath(endpoint)
                    .WithMethod(HttpMethod.Get);

                // Send the request and get the response
                FluentHttpResponse response = await request.SendAsync();

                // Parse the JSON response
                JObject json = JObject.Parse(await response.Content.ReadAsStringAsync());

                // Return the response and the parsed JSON
                return (response, json);
            }).ToArray();

            // Wait for all requests to complete
            (FluentHttpResponse response, JObject json)[] results = await Task.WhenAll(tasks);
        }

        public Form1()
        {
            InitializeComponent();
        }
    }
}
=> But I got some compiler errors: Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS1061	'FluentHttpRequestBuilder' does not contain a definition for 'WithPath' and no accessible extension method 'WithPath' accepting a first argument of type 'FluentHttpRequestBuilder' could be found (are you missing a using directive or an assembly reference?)
Error	CS1061	'FluentHttpRequest' does not contain a definition for 'SendAsync' and no accessible extension method 'SendAsync' accepting a first argument of type 'FluentHttpRequest' could be found (are you missing a using directive or an assembly reference?)	
=> Since I don't know what FluentlyHttpClient.Entity is doing, so I try to avoid to use this. I also tried to update some dependencies to use latest version of nuget package, like: newtonsoft.json; but one nuget package: Sketch7.core (0.1.1) seems to be too old to get update.  So I want to not using any FluentlyHttpClient.Entity code.  Please advise if you can change my code and make it working. 
Thanks,

**Comment by Pathoschild** [comment]
AI isn't very good at writing code like that yet.

There's several ways to do it, but here's one approach if you're using a Windows Form app:

1. Reference the `Pathoschild.Http.FluentClient` package. You don't need any other packages for this (it'll handle the JSON parsing for you).
2. Create a class which matches the API response. Here's a quick one based on the [WorldTime API example](https://worldtimeapi.org/). (You can optionally delete any fields you won't use.)
   ```cs
   public class WorldTimeModel
   {
       public string abbreviation { get; set; }
       public string client_ip { get; set; }
       public string datetime { get; set; }
       public int day_of_week { get; set; }
       public int day_of_year { get; set; }
       public bool dst { get; set; }
       public string dst_from { get; set; }
       public int dst_offset { get; set; }
       public string dst_until { get; set; }
       public int raw_offset { get; set; }
       public string timezone { get; set; }
       public int unixtime { get; set; }
       public string utc_datetime { get; set; }
       public string utc_offset { get; set; }
       public int week_number { get; set; }
   }
   ```
3. Fetch all the time zones from the API and handle the data.
   ```cs
   // fetch data
   string[] timezones = { "Europe/London", "Europe/Berlin", "America/New_York" };
   using var client = new FluentClient("https://worldtimeapi.org/api/timezone/");
   Task<WorldTimeModel>[] tasks = timezones
       .Select(timezone => client.GetAsync(timezone).As<WorldTimeModel>())
       .ToArray();
   Task.WaitAll(tasks);

   // handle the data
   foreach (Task<WorldTimeModel> task in tasks)
   {
       WorldTimeModel data = task.Result;

       Console.WriteLine($"Time zone '{data.timezone}' has UTC offset '{data.utc_offset}'.");
   }
   ```

The `tasks` array will now contain data like this:
![image](https://github.com/Pathoschild/FluentHttpClient/assets/230581/de27da4b-a22c-40a5-bda0-cb5b6ccc5481)

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your help. Your code works.  But since the lastest version of Nuget package was released 9 moths ago; after .net 8.0 released, is it possible to release a new NUGET pacakge  to target .net 8.0? Since .net 8.0 is in long term support.  So I don't have to change it for quite a few years.
Or if you can provide some general instructions, I could try to upgrade it to target .net 8.0.  Thanks,

**Comment by Pathoschild** [comment]
The package targets .NET 5 because it's forward-compatible with later versions. It's fully compatible with .NET 5 through 8 without needing to specifically target each version.

**Comment by zydjohnHotmail** [comment]
OK, thanks!
