### ISSUE TITLE
Hardcoded User-Agent

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#12]
I see two problems with the user-agent:

1. The value is hard-coded (in Factory.cs, on line 45) and I can't provide my own string if desired. I understand the need for a default value in case the developer doesn't care about this string, but I should be able to override it if I want.
2. The current hard coded value starts with: `FluentHttpClient/0.4`. The problem is that the version number is hard coded and does not reflect the actual version number of the FluentHttpClient library.

I propose the following:

1. Remove the hard-coded user-agent string
2. Add a new `UserAgentFilter` class. This class will, by default, use ""FluentHttpClient/x.x.x (+http://..." and x.x.x will be automatically replaced with the FluentClient assembly version.
3. Add a new `public void SetUserAgent(string useragent)` method to IClient and Client.cs which will replace the default user agent filter with one that uses the provided custom string

I will be happy to submit a PR

**Comment by Pathoschild** [comment]
Sounds good! Submit the PR and I'll include it in the 2.3 release.

See also my proposal in #10, which would make this easier.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming 2.4 release. Thanks!
