### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#121]
The integration tests that download data from Wikipedia are failing, presumably because the data returned no longer matches the expected data:

![image](https://github.com/Pathoschild/FluentHttpClient/assets/112710/382827b9-80b5-414d-9ca1-d7a7674be9cd)

```
Unexpected value for p.MaxUploadSize
  Expected: 4294967296
  But was:  5368709120
```

**Comment by Pathoschild** [comment]
Merged into `develop`. Thanks for the help!
