### ISSUE TITLE
System.Text.Json - json formatter

### ISSUE THREAD

**Issue by djgrech** [Pathoschild/FluentHttpClient#128]
Does this library support `System.Text.Json` serialization out of the box? Or is there a way how to use `System.Text.Json` it instead of `Newtonsoft `

Thank you

**Comment by Pathoschild** [comment]
Hi! The fluent client uses the same formatters as .NET's built-in `HttpClient` by default (i.e. Newtonsoft).

You can easily [change the format](https://github.com/Pathoschild/FluentHttpClient?tab=readme-ov-file#custom-formats) like this:
```cs
client.Formatters.Remove(client.Formatters.JsonFormatter);
client.Formatters.Add(new ...());
```

.NET doesn't seem to have an official media type formatter using `System.Text.Json` yet, but you could try [searching NuGet for third-party implementations](https://www.nuget.org/packages?q=MediaTypeFormatter+System) or create your own.

That said, note that `System.Text.Json` is much stricter than Newtonsoft.Json. While that results in better performance, it will also throw an exception at the slightest deviation from the strict JSON spec.
