### ISSUE TITLE
Refactor the FluentClient constructor

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#17]
I suggest combining the two overloaded constructors:
```
public FluentClient(string baseUri)
public FluentClient(string baseUri, HttpClient client)
```
into a single one:
```
public FluentClient(string baseUri, HttpClient client = null)
```

Also, I suggest adding a new constructor that allows specifying the baseUri as `Uri` instead of a string:
```
public FluentClient(Uri baseUri, HttpClient client = null)
```
I will submit a PR.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming 2.4 release. Thanks!
