### ISSUE TITLE
Async methods should accept a concellation token

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#24]
The cancellation token allows a long running async method to be cancelled but the FluentClient currently does not accept such a token. I propose adding a parameter for the token to methods such as `DeleteAsync`, `GetAsync`, `SendAsync`, etc.. Of course this parameter should be optional.

I will submit a PR.

**Comment by Pathoschild** [comment]
Done in `develop` via PR #25 for the upcoming 2.4 release. Thanks!
