### ISSUE TITLE
Filters property missing from IClient interface

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#28]
I noticed that the Filters property is on the FluentClient class but not on the IClient interface. Is that intentional or an oversight? What makes me think it is probably an oversight is that a similar property called Formatters is on the IClient interface and also on the FluentClient class (which I think is correct).

If it's simply an oversight, I'll be happy to submit a PR to correct it.

**Comment by Pathoschild** [comment]
Makes sense, feel free to submit a PR.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming 2.4 release. Thanks!
