### ISSUE TITLE
Request interface not as simple as could be

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#32]
The IRequest interface has three overloads for the `WithBody` method (to be more accurate: there are 2 overloads and the third method is called `WithBodyContent`). Only `WithBodyContent` should be on the interface and the other two methods should be extension methods since they invoke WithBodyContent.

This is similar to the work that was done to simplify the IClient interface as discussed in #26.

Will submit PR.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming 2.4 release. Thanks!
