### ISSUE TITLE
Missing methods for authentication on IClient interface

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#33]
In PR #15 I added `SetAuthentication` to IClient and `WithAuthentication` to IRequest. I also added two convenient extension methods `WithBasicAuthentication` and `WithBearerAuthentication` to IRequest.

However, I forgot to add similar extension methods to the IClient interface.

Will submit PR.

**Comment by Pathoschild** [comment]
Merged into `develop` for the upcoming 2.4 release. Thanks!
