### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/FluentHttpClient#37]
The client uses the [CC-BY 3.0 license](https://creativecommons.org/licenses/by/3.0/), which [isn't well-suited to software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software). That makes redistributing software with the fluent client legally ambiguous, which wasn't the intention.

I propose switching to the [MIT license](https://choosealicense.com/licenses/mit/). Any objections? I'll need specific permission from each significant contributor to relicense their contributions:

* [x] @dwfrancis
* [x] @Jericho 
* [x] @lostdev
* [x] @Pathoschild

**Comment by Jericho** [comment]
I agree with switching to MIT license.

**Comment by dwfrancis** [comment]
No objections here.

**Comment by lostdev** [comment]
That's fine by me as well.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming 3.0 release. Thanks!
