### ISSUE TITLE
Default headers

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#51]
I am porting my second library to FluentHttpClient and noticed a missing feature: I can't set a default header that gets automatically added to every request. I know that I can invoke the `IRequest.WithHeader(string key, string value)` for each request, but it's very tedious.

I propose adding a method to IFluentClient like so:
```CSharp
        /// <summary>Adds a header which should be sent with each request.</summary>
        /// <param name="name">The name of the header.</param>
        /// <param name="value">The value of the header.</param>
        public IClient SetHeader(string name, string value)
        {
            this.BaseClient.DefaultRequestHeaders.Add(name, value);
            return this;
        }
```

**Comment by Pathoschild** [comment]
The same applies to other request options; how about a catchall method? For example:

```cs
client.SetDefaultRequestOptions(request => request.WithHeader(…));
```

**Comment by Jericho** [comment]
It would accept a single lambda parameter which would get invoked right before a request yields a response, right? As long as it's in addition to `SetHeader`,

I'll submit PR for `SetHeader` and will let you submit PR for `SetDefaultRequestOptions`.

**Comment by Pathoschild** [comment]
I added `client.AddDefault` to specify default request options in the upcoming 3.1. The lambda is applied in `client.SendAsync` when creating the request, before it's returned for chaining.
```cs
// set default header
client.AddDefault(req => req.WithHeader(…));

// create request (default header is set by this point)
IRequest request = client.GetAsync(…);
```

Does this address your use case? (And if not, why not?)

**Comment by Jericho** [comment]
This discussion was from 7 months ago. I don't really remember what my use case was but what I ended up doing is something like this:
```
client.BaseClient.DefaultRequestHeaders.Add("myHeader", "abc123");
```
which has worked fine for me for the last 7 months. The PR I submitted in Feb 2017 would simplify the syntax by allowing the following:
```
client.SetHeader("myHeader", "abc123");    // Update the header is present or add it if not already present
client.AddHeader("myHeader", "abc123");    // Add the header even if a header with the same name already exist
```

but since I have a work around, the simpler syntax is no longer a priority for me.

**Comment by Pathoschild** [comment]
I'll close this as done using the `AddDefault` method then.
