### ISSUE TITLE
Support for multiple query parameters with the same name

### ISSUE THREAD

**Issue by EricStG** [Pathoschild/FluentHttpClient#54]
Looking at Request.GetArguments, which is called from WithArguments, it looks like I need to pass either an object or an IDictionary to the method in order to setup the query string.

Unfortunately, the API I'm calling requires me to enter the same parameter with multiple different values.
Ex: http://service/foo?bar=1&bar=2

Would it be problematic to use IEnumerable<KeyValuePair<>> Instead of IDictionary within that class?

**Comment by Pathoschild** [comment]
Hi @EricStG. `WithArguments(…)` is just a shortcut for `WithArgument(key, value)`, which does what you want:

```cs
IRequest request = client
   .GetAsync("foo")
   .WithArgument("bar", 1)
   .WithArgument("bar", 2);

// request.Message.RequestUri is http://service/foo?bar=1&bar=2
```

You can also use them together if you want:
```cs
IRequest request = client
   .GetAsync("foo")
   .WithArgument("bar", 1)
   .WithArguments(new { bar = 2, foobar = 3, quux = 4 });

// request.Message.RequestUri is http://service/foo?bar=1&bar=2&foobar=3&quux=4
```

**Comment by EricStG** [comment]
I should've paid more attention. Thanks!

**Comment by Pathoschild** [comment]
Welcome!
