### ISSUE TITLE
how to use client with TestSever

### ISSUE THREAD

**Issue by Cuiqs76** [Pathoschild/FluentHttpClient#55]
Is there a way to you asp.net core TestServer?

` var builder = new WebHostBuilder()
                 .UseStartup<Startup>();
            var _server = new TestServer(builder);

            _handler = _server.CreateHandler();
            _client = _server.CreateClient();`

**Comment by Pathoschild** [comment]
Yep. The fluent client is just a wrapper around HttpClient, and you can set the client to use:

```cs
var builder = new WebHostBuilder().UseStartup();
var _server = new TestServer(builder);
var client = new FluentClient("https://example.org/api/", _server.CreateClient());
```
