### ISSUE TITLE
OData feeds raise an exception 

### ISSUE THREAD

**Issue by moh-hassan** [Pathoschild/FluentHttpClient#57]
**example:**
 
            var url = "http://services.odata.org/V4/Northwind/Northwind.svc/";
            IClient client = new FluentClient(url);
            var customers = await client
					   .GetAsync("Customers")
					    .AsArray<Customer>(); 
            Console.WriteLine(item.Length);
      
		
**Error Message:**

       InnerException: 
         HResult=-2146233088
       Message=Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'NorthwindModel.V4.Customer[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
           To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized  type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
           Path '['@odata.context']', line 1, position 18.
           Source=Newtonsoft.Json

Also, I can't capture the exception when using try .. catch{}. The exception isn't reached.

It seems that the default json deserializer can't handle arrays in OData feeds, because OData feeds are different than REST services.
 
Edit: 
Customer is POCO

		public class Customer
			{
				public string CustomerID { get; set; }  
				public string CompanyName { get; set; }  
				public string ContactName { get; set; }
				public string ContactTitle { get; set; }
				public string Address { get; set; }
				public string City { get; set; }
				public string Region { get; set; }
				public string PostalCode { get; set; }
				public string Country { get; set; }
				public string Phone { get; set; }
				public string Fax { get; set; }
			}

**Comment by Jericho** [comment]
The issue is that you are asking FluentHttpClient to convert the response into an array of Customers but the response follows the [OData format](http://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html) and therefore it contains a JSON object which looks like this:

```
{
    "@odata.context":"http://services.odata.org/V4/Northwind/Northwind.svc/$metadata#Customers",
    "value":[ ... the customers ... ],
    "@odata.nextLink":"Customers?$skiptoken='ERNSH'"
}
```

As you can see, the data you are interested in is in the `value` property. What you need to do is extract the content of the `value` property and convert it into an array of the desired type. 

Here's how I would do it:

```csharp
public static Task<T[]> AsODataArray<T>(this IResponse response)
{
    return response.Message.Content.AsODataArray<T>();
}

public static async Task<T[]> AsODataArray<T>(this IRequest request)
{
    var response = await request.AsMessage().ConfigureAwait(false);
    return await response.Content.AsODataArray<T>().ConfigureAwait(false);
}

private static async Task<T[]> AsODataArray<T>(this HttpContent httpContent)
{
    var responseContent = await httpContent.ReadAsStringAsync().ConfigureAwait(false);

    var jObject = JObject.Parse(responseContent);
    return jObject["value"].ToObject<T[]>();
}
```

And I would use it like so:
```csharp
var url = "http://services.odata.org/V4/Northwind/Northwind.svc/";
IClient client = new FluentClient(url);
var customers = await client
        .GetAsync("Customers")
        .AsODataArray<Customer>(); 
Console.WriteLine(customers.Length);
```

**Comment by moh-hassan** [comment]
Fantastic and clean solution :)
  Your OData extension method  ".AsODataArray" solved  the problem and I can say that my issue is resolved.
Thank you very much for help and support.
