### ISSUE TITLE
Retry coordinator should handle timeouts

### ISSUE THREAD

**Issue by datgrog** [Pathoschild/FluentHttpClient#58]
Hello,

I just open a post on [stackoverflow](https://stackoverflow.com/questions/44800671/how-to-use-setrequestcoordinator-from-pathoschild-lib) because it's seems I don't use properly the retry feature.
I don't know if its an issue or if I just don't use it correctly.

Best

**Comment by Pathoschild** [comment]
Hi @onepix. That's an oversight in the new retry coordinator — it retries if the server returns an error, but not if the request times out locally. I'll fix that in the next release. :)

**Comment by datgrog** [comment]
Thank you very much. 👍

**Comment by Pathoschild** [comment]
Done in the upcoming 3.1 release.
