### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#62]
Hi @Pathoschild,

just curious if you are still maintaining this project? I haven't seen any activity in a while so I was wondering. If you are, any chance you can look at the PR I submitted last week regarding issue with the retry coordinator?

Thanks

**Comment by Pathoschild** [comment]
Yep, though I'm mainly focusing on [SMAPI 2.0](https://github.com/Pathoschild/SMAPI) for the next little while. I'll go through the backlog here this weekend. :)
