### ISSUE TITLE
Unit tests no longer discovered by Visual Studio 2017

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#64]
Is it just me or the unit tests no longer show up under "Test Explorer"?

![image](https://user-images.githubusercontent.com/112710/30245938-0a9f67a8-95b8-11e7-8d6c-132196e27e25.png)

According to [this article](https://stackoverflow.com/questions/43007761/how-to-run-nunit-tests-in-visual-studio-2017), we are probably missing a reference to the NUnit test adapter.

I'll add the missing reference and submit PR in a few minutes.

**Comment by Pathoschild** [comment]
They work for me, but I use ReSharper to run unit tests. The built-in test explorer may work differently.

**Comment by Jericho** [comment]
Sure enough: I added a reference to `NUnit3TestAdapter` and all unit tests automatically showed up:

![image](https://user-images.githubusercontent.com/112710/30245957-cf0fc484-95b8-11e7-85f2-bc428d0e14dd.png)

**Comment by Pathoschild** [comment]
Merged. Thanks!
