### ISSUE TITLE
Retrying too many times (3.1 beta)

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#67]
While testing release 3.1 I noticed that one of my project's unit tests is failing. My test is checking that FluentHtpClient is retrying exactly 5 times but it appears that it's retrying 6 times.

```
[Fact]
public async Task Retry_failure()
{
	// Arrange
	var baseUri = "https://api.vendor.com/";
	var resource = "testing";

	var mockHttp = new MockHttpMessageHandler();
	mockHttp.Expect(HttpMethod.Get, baseUri + resource).Respond((HttpStatusCode)429);
	mockHttp.Expect(HttpMethod.Get, baseUri + resource).Respond((HttpStatusCode)429);
	mockHttp.Expect(HttpMethod.Get, baseUri + resource).Respond((HttpStatusCode)429);
	mockHttp.Expect(HttpMethod.Get, baseUri + resource).Respond((HttpStatusCode)429);
	mockHttp.Expect(HttpMethod.Get, baseUri + resource).Respond((HttpStatusCode)429);

	var httpClient = mockHttp.ToHttpClient();
	var client = new FluentClient(baseUri, httpClient);
	client.SetRequestCoordinator(
		maxRetries: 5,
		shouldRetry: res => res.StatusCode == (HttpStatusCode)429,
		getDelay: (attempt, res) => TimeSpan.Zero
	);

	// Act
	var result = await Should.ThrowAsync<Exception>(async () => await client.SendAsync(HttpMethod.Get, resource).AsResponse().ConfigureAwait(false)).ConfigureAwait(false);

	// Assert
	mockHttp.VerifyNoOutstandingExpectation();
	mockHttp.VerifyNoOutstandingRequest();

	result.Message.ShouldBe("The HTTP request failed, and the retry coordinator gave up after the maximum 5 retries");
}
```

This unit test was working fine in 3.0 but it is now throwing the following exception: `No matching mock handler`. My guess is that the logic in the retry coordinator has changed and instead of attempting the request 5 times (which was the logic in 3.0) it is now attempting the request 5 times **IN ADDITION** to the initial attempt (for a total of 6 attempts).

**Comment by Pathoschild** [comment]
Yep, the retry logic was rewritten in 3.1. The `maxRetries` value now correctly sets the number of _retries_ instead of _attempts_.

**Comment by Jericho** [comment]
That's a breaking change as evidenced by the fact that I will need to rewrite my unit test and my code that sets the number of attempts. Should at least be documented in release notes.

**Comment by Pathoschild** [comment]
Almost any change will break some conceivable usage. For example, retrying timeouts at all is a breaking change for anyone who depends on them failing. I think it's important to have a more nuanced definition of 'breaking change'.

The change breaks your unit test because you're testing an implementation detail of the library. The effect on actual users is likely to be corrective (e.g. for users who set `maxRetries: 1` and expect it to retry) or neutral (worst case: the client retries once more). I don't foresee this being a breaking change outside of specific unit tests.

**Comment by Jericho** [comment]
I'm not trying to argue semantics: call it a change in behavior if you prefer or even a bug fix if you consider the original behavior was not as you intended (I personally was happy with the original behavior). I'm just trying to point out that something changed and it affected me and there was no issue on GitHub that would have alerted me nor any mention of it in the release notes. And I didn't read any comment about it in the code either so, to be honest, I didn't even know if this change was intentional or not. That's why I said this change should at least be documented.

**Comment by Pathoschild** [comment]
I added it to the release notes when you first mentioned it; sorry about that. :)

**Comment by Jericho** [comment]
Do you mind if I suggest we add more details to the release notes? The current entry you added is not very clear to me.

I propose something like:
* Fixed `IRetryConfig.MaxRetries`: this value now sets the number of retries beyond the initial request. Previously, this value represented the total number of attempts, including the initial request.

**Comment by Pathoschild** [comment]
How about this?
> Fixed `IRetryConfig.MaxRetries` counting the initial request as a retry (e.g. `maxRetries: 1` never retried).

**Comment by Jericho** [comment]
Maybe it's just me, but I feel like this change can be easily overlooked and it deserves a little more details

> Fixed IRetryConfig.MaxRetries counting the initial request as a retry which meant that maxRetries: 1 never retried. This value now sets the number of retries beyond the initial request.

**Comment by Pathoschild** [comment]
The `maxRetries: 1` case is only an example (e.g. `maxRetries: 2` was also incorrect). Slight tweak to reflect that:

> Fixed `IRetryConfig.MaxRetries` counting the initial request as a retry (e.g. `maxRetries: 1` never retried). This value now sets the maximum number of retries after the initial request.

**Comment by Jericho** [comment]
Very good.

**Comment by Pathoschild** [comment]
Release notes updated.
