### ISSUE TITLE
Add FluentHttpClient to nuget tags

### ISSUE THREAD

**Issue by HeyJoel** [Pathoschild/FluentHttpClient#69]
Hi, I wanted to try out your library but had trouble finding it in the nuget search when typing in "fluent http client", and then "FluentHttpClient".  The package name is different from the repo so maybe you should add FluentHttpClient to the nuget tags.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming 3.1 release. Thanks for the suggestion!
