### ISSUE TITLE
Ignore Null Arguments

### ISSUE THREAD

**Issue by mrUlrik** [Pathoschild/FluentHttpClient#80]
I am passing a model that contains a reference to a list  of a list of strings whose child values can be null.

```
    public class Payload
    {
        [JsonProperty("Constraints")] public Constraints Constraints { get; set; }
        [JsonProperty("OtherThings")] public string OtherThings { get; set; }
    }

    public class Constraints
    {
        [JsonProperty("ReallyDumbList")] public List<List<string>> ReallyDumbList { get; set; }
    }
```

Despite setting this to ignore null arguments the JSON payload still contains a null list. The Constraints property is not populated or even referenced when creating the Payload object. I am currently playing with the following:

```
var payload = new Payload {
    OtherThings = "Other Values"
}

Client = new FluentClient($"http://localhost/");
Client.Formatters.JsonFormatter.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Ignore;
Client.Formatters.JsonFormatter.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
Client.SetOptions(ignoreNullArguments: true);
await Client.PutAsync($"myapi/", payload);
```

This produces:

```
  "Constraints": {
    "ReallyDumbList": [],
    "OtherThings": "Other Values"
  }
```

Unfortunately that is not allowed by the remote API I am trying to use. I need "ReallyDumbList" to not appear in the JSON payload.

**Comment by Pathoschild** [comment]
@mrUlrik The problem is that the list is empty, not `null`. I tried your sample code and it produced the expected request body:
```json
{"OtherThings":"Other Values"}
```
Are you initialising the list somewhere not shown in your sample code?

**Comment by mrUlrik** [comment]
Thank you very much. This was a problem with my code. The nature of dealing with nested lists that my brain just did not do the simple addition on. Thank you very much for discovering this for me. :)

**Comment by Pathoschild** [comment]
Happy to help!
