### ISSUE TITLE
A breaking change for a proxy settings in 3.2

### ISSUE THREAD

**Issue by zllvm** [Pathoschild/FluentHttpClient#81]
After an update to a new version 3.2, I got timeouts in my projects. Apparently, if there is no WebProxy or HttpClient provided, the default behavior no longer allows to use default proxy settings. 

From FluentClient.cs:

```
private static HttpClientHandler GetDefaultHandler(IWebProxy proxy = null)
        {
            return new HttpClientHandler
            {
                // configure proxy
                Proxy = proxy,
                UseProxy = proxy != null,

                // don't use cookie container (so we can set cookies directly in request headers)
                UseCookies = false
            };
}
```

Thereby, proxy will be set to false. 

If it is a supposed way of doing, then it could be good to mention it in the release notes.

**Comment by Pathoschild** [comment]
@zllvm Overriding the default proxy isn't intended; I'll fix that in the next release. Can you try setting the default proxy as a temporary workaround?

```cs
var client = new FluentClient(uri, WebRequest.DefaultWebProxy);
```

**Comment by zllvm** [comment]
Right, I've done this fix already, works fine. Thanks for a quick reply!

**Comment by zllvm** [comment]
The solution with WebRequest.DefaultWebProxy does not work in net core. It requires a null value set for HttpClientHandler.Proxy.

**Comment by Pathoschild** [comment]
@zllvm Here's a build which should fix the issue (see [how to install a local package](https://stackoverflow.com/questions/10240029/how-do-i-install-a-nuget-package-nupkg-file-locally)). If that works fine for you, I'll release it as 3.2.1.

Attached:
* [Pathoschild.Http.FluentClient.3.2.1-alpha-20180727.nupkg.zip](https://github.com/Pathoschild/FluentHttpClient/files/2237018/Pathoschild.Http.FluentClient.3.2.1-alpha-20180727.nupkg.zip)

**Comment by zllvm** [comment]
@Pathoschild Yes, it has fixed it. Thanks!

**Comment by Pathoschild** [comment]
This is included in the upcoming release.
