### ISSUE TITLE
Simplify form-URL-encoded content

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/FluentHttpClient#85]
APIs often take form-URL-encoded bodies as input, but those are a bit awkward currently:
```cs
await client
    .PostAsync("blogs")
    .WithBodyContent(new FormUrlEncodedContent(new[]
    {
        new KeyValuePair<string, string>("title", "Example title"),
        new KeyValuePair<string, string>("category_id", category.ToString())
    });
```

Consider adding convenience methods.

**Comment by Pathoschild** [comment]
Some possible designs:
```cs
// builder
await client
    .PostAsync("blogs")
    .WithBodyContent(p => p.FormUrlEncoded(new
    {
        title = Example title,
        category_id = category
    }));

// body wrapper
await client
    .PostAsync("blogs")
    .WithBodyFormUrlEncoded(new
    {
        title = Example title,
        category_id = category
    });

// argument wrappers
await client
    .PostAsync("blogs")
    .WithBodyFormUrlEncodedArgument("title", "Example title")
    .WithBodyFormUrlEncodedArgument("category_id", category);
```

**Comment by Jericho** [comment]
You and I had a discussion about URL encoded form content about two years ago. [Here’s the extension method](
https://github.com/Pathoschild/FluentHttpClient/issues/50#issuecomment-279249618) I came up with at the time which has served me well since then.

**Comment by Pathoschild** [comment]
Thanks! That ticket got closed as a question, but I think it's common enough that we could support it directly in the client. I also prefer the simplicity of setting arguments using the anonymous object syntax, instead of a collection of `KeyValuePair`s.

**Comment by Jericho** [comment]
The reason I picked IEnumerable rather than IDictionary or anonymous object was that I needed to support multiple arguments with same name. This is the same reasoning that explains why there are two overloads of the WithArguments method: one accepts IEnumerable<KeyValuePair> and the second accepts an object. You should consider doing the same

**Comment by Pathoschild** [comment]
Yep, it'll support both just like `WithArguments`. Leaning towards this syntax, since it's easy to extend with other formats:
```cs
// unique arguments
await client
    .PostAsync("blogs")
    .WithBody(p => p.FormUrlEncoded(new
    {
        title = Example title,
        category_id = category
    }));

// repeating arguments
await client
    .PostAsync("blogs")
    .WithBody(p => p.FormUrlEncoded(keyValuePairs));
```

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming FluentHttpClient 3.3. This...

* Adds a `WithBody` builder overload:
  > ![image](https://user-images.githubusercontent.com/230581/56715606-2e8d7d00-6706-11e9-86a3-40145a4dff15.png)

* Adds a simpler `WithBody` method for the most common case:
   ```cs
   request.WithBody<T>(T body);
   ```

* Marks these methods deprecated:
  ```cs
  request.WithBodyContent(HttpContent body);
  request.WithBody<T>(T body, MediaTypeHeaderValue contentType = null);
  request.WithBody<T>(T body, MediaTypeFormatter formatter, string mediaType = null);
  ```

The deprecations bring us down to two overloads, so it's less confusing while still supporting all previous cases:
```cs
request.WithBody<T>(T body);
request.WithBody(Func<IBodyBuilder, HttpContent> bodyBuilder);
```

Let me know if you want to change anything!
