### ISSUE TITLE
Change package ID?

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/FluentHttpClient#87]
Consider changing the package ID in a future version to match the library name (from `Pathoschild.Http.FluentClient` to `Pathoschild.FluentHttpClient`).

**Comment by Pathoschild** [comment]
## Background
FluentHttpClient is the top Google result for "FluentHttpClient", but it's _way_ down the list in the Visual Studio package manager (which mainly searches the package ID):
> ![image](https://user-images.githubusercontent.com/230581/56845193-2b6fc980-688b-11e9-9be9-cc7d8fa8582e.png)

It's near the top for "FluentClient" though, since that's in the ID (no idea why a package with 73 downloads is first):
> ![](https://user-images.githubusercontent.com/230581/56845202-59550e00-688b-11e9-9d9d-e0572c069589.png)

## Pros & cons
* Pros:
  * Less confusing when users search "FluentHttpClient".
  * ID is more logical and consistent going forward.
* Cons:
  * Resets downloads to zero, which decreases visibility.
  * Existing users need to uninstall the old package, and install the new one.

Ideally NuGet would support renaming a package, but that seems unlikely since they've closed all previous proposals to implement it. We might have [package deprecation](https://github.com/NuGet/Home/issues/2867) soon though.

**Comment by Huntk23** [comment]
Perhaps this is no longer a problem? When I search `FluentHttpClient` it is 3rd in my list.

![image](https://user-images.githubusercontent.com/3951241/178592294-7a96d581-73e9-44a6-af07-49dee53b2271.png)

**Comment by Pathoschild** [comment]
Yeah, and it doesn't seem like we'll ever have a good way to change NuGet package IDs, so I think we can close this.
