### ISSUE TITLE
Using client X.509 certificate with FluentHttpClient

### ISSUE THREAD

**Issue by rajeevmv** [Pathoschild/FluentHttpClient#90]
Is there a way to specify a client X.509 certificate for the FluentHttpClient to use for mutual TLS authentication?

**Comment by Pathoschild** [comment]
Yep. The library wraps the underlying `HttpClient`, so you can init a message handler with the certificate and pass that to the fluent client:
```cs
var certificate = new X509Certificate2(...);
var messageHandler = new HttpClientHandler
{
    ClientCertificateOptions = ClientCertificateOption.Manual,
    ClientCertificates = { certificate }
};
var client = new FluentClient(baseUrl, client: new HttpClient(messageHandler));
```

See [this StackOverflow question](https://stackoverflow.com/q/40014047/262123) (.NET Standard 1.3+) and [this other one](https://stackoverflow.com/q/47020011/262123) (.NET Framework 4.5–4.7) for more info.

**Comment by rajeevmv** [comment]
Thanks for the quick response.
