### ISSUE TITLE
Breaking change in WithBody

### ISSUE THREAD

**Issue by PauliusLe** [Pathoschild/FluentHttpClient#93]
I noticed there is undocumented breaking change in 4.0.0. Not sure if it was intentional but after [this](https://github.com/Pathoschild/FluentHttpClient/commit/61727a553acdda576ea7c792df5a2720f5ae1d2d) commit `WithBody<T>(this IRequest request, T body)` no longer accepts nulls. If it was intentional it should be documented. But I think it should accept nulls.

**Comment by Pathoschild** [comment]
Fixed in the upcoming 4.0.1. Thanks for reporting it!
