### ISSUE TITLE
how to with jwt ？？？

### ISSUE THREAD

**Issue by icetech233** [Pathoschild/FluentHttpClient#95]
how to with jwt ？？？ IdentityServer4

**Comment by Jericho** [comment]
I don't understand your question. Can you explain?

**Comment by Pathoschild** [comment]
JWTs are usually sent as bearer tokens (though it depends on your server configuration). Once you create the token with a library like `System.IdentityModel.Tokens.Jwt`, you can set it for all requests:

```cs
client.SetBearerAuthentication(jsonWebToken);
```

Or for a single request:
```cs
Blog result = await new FluentClient("https://example.org/api")
   .GetAsync("blogs")
   .WithBearerAuthentication(jsonWebToken)
   .As<Blog>();
```
