### ISSUE TITLE
How should i do with retry policy?

### ISSUE THREAD

**Issue by weiwxg** [Pathoschild/FluentHttpClient#96]
First problem is how do I use the retry mechanism for the returned object, rather than http status, as follow:
```csharp
await PostAsync(uri, res => !res.Result, TimeSpan.FromSeconds(1));
```
Sencondly, if i want to do somthing other like refresh cache before retry, how can i do?

**Comment by Pathoschild** [comment]
Hi! You can [create a request coordinator](https://github.com/Pathoschild/FluentHttpClient#custom-retrycoordination-policy) to change how the request is sent. That lets you run code before/after the request, read the response to decide how to handle it, update your cache, resend the request, etc. For example, the default retry feature is just [a coordinator that resends the request a few times](https://github.com/Pathoschild/FluentHttpClient/blob/develop/Client/Retry/RetryCoordinator.cs#L50-L79).
