### ISSUE TITLE
How to Post with FormData?

### ISSUE THREAD

**Issue by weiwxg** [Pathoschild/FluentHttpClient#97]
i use PostAsync(uri).WithArgument("","") ... get 400 bad request.

**Comment by weiwxg** [comment]
![image](https://user-images.githubusercontent.com/24971860/103518662-201dcf80-4eaf-11eb-88a6-4f5fb86310c6.png)

**Comment by Jericho** [comment]
Judging from the screenshot you posted, it looks like the API you are interacting with expects 3 properties (i.e. `client_id`, `client_secret` and `grant_type`) to be posted in the body of your request and furthermore it expects this data to be "URL encoded". However, the short code sample you posted indicates that you are appending the arguments to the querystring. The fact that you are not posting the data according to the API expectations explains why you are getting a `HTTP 400` response.

The good news is that I also interact with an API that expects data to be URL encoded so I can share with you how I do it. The FluentHttpClient has a `WithBody` method that allows you to pass your parameters in the body of your request (which is what the API you are using requires) and, very importantly, also allows you to specify how the data should be encoded (in the case of the API you are using, the data must be "URL encoded" as opposed to the default which is "JSON").

So, step one is to prepare the parameters for your request. Here's how I do it:
```csharp
var parameters = new Dictionary<string, string>
{
    { "client_id", myClientId },
    { "client_secret", myClientSecret },
    { "grant_type", myGrantType }
};
```

Step two is to prepare the request you will send to the API, making sure to specify that you want the parameters to be URL encoded. Here's how I do it:
```csharp
var request = myFluentHttpClient
    .PostAsync(myUrl)
    .WithBody(bodyBuilder => bodyBuilder.FormUrlEncoded(parameters));
    .WithCancellationToken(myCancellationToken)
```

And finally, step 3 is to dispatch your request to the API and to parse the response according to the the expected format. The screenshot you posted does not show the type of the response and I couldn't guess what it looks like so you will need to adjust the following code according to your API's documentation:
```csharp
var response = await request // <-- dispatch the request to the API
    .AsString() // <-- depending on the data returned by the API you may prefer AsStream, AsRawJson, AsRawJsonArray, etc.
    .ConfigureAwait(false);
```

I hope this helps.

**Comment by Pathoschild** [comment]
Expanding on Jericho's answer, you can also do everything in one go if you want:

```cs
var response = await client
    .PostAsync(myUrl)
    .WithBody(builder => builder.FormUrlEncoded(new
    {
        client_id = myClientId,
        client_secret = myClientSecret,
        grant_type = myGrantType
    }))
    .AsString()
    .ConfigureAwait(false); // <-- not needed if you're using it in your app directly
```

**Comment by weiwxg** [comment]
great! very useful to me, thanks!
