### ISSUE TITLE
The API query failed with status code NotAcceptable: Not Acceptable

### ISSUE THREAD

**Issue by weiwxg** [Pathoschild/FluentHttpClient#98]
i use `await httpClient.GetAsync("http://..../demo.jpg")` throw 406 Not Acceptable

**Comment by Jericho** [comment]
You provide so little information, it's very hard for us to guess what could be going on. I understand you want to obfuscate the URL for privacy reasons but it makes it impossible for us to reproduce the problem. Therefore we are relying on you to provide additional info.

What have you tried so far during your investigation? 

Can you you share your C# code with us (more than the short snippet included in your question)?

Have you been able to successfully retrieve `demo.jpg` using a different tool like your browser for example? Have you tried Fiddler? Postman? Any other tool? If so, have you been able to compare the requests and noticed any difference? Can you share with us the http requests/responses captured by the tool you are using so we can help you comparing them?

Have you been able to to retrieve other jpgs on this web site? Have you been able to retrieve images from other web sites?

In the mean time, I wrote the following to demonstrate that you can download Google's logo from their web site: 

```csharp
IClient client =  new FluentClient("https://www.google.com");

byte[] response = await client
    .GetAsync("images/branding/googlelogo/1x/googlelogo_color_272x92dp.png")
    .AsByteArray()
    .ConfigureAwait(false);

// Save the image to the temp folder so we can look at it
string tempFilePath = Path.ChangeExtension(Path.GetTempFileName(), "png");
File.WriteAllBytes(tempFilePath, response);
```

**Comment by weiwxg** [comment]
i have a jpg resouce : http://ezcardfile1.namex.cn/UploadFile/user/product/picture2101/328E09727F55A7876AF4731294706D80_2.jpg
and i can display it in browser.
but when i get it as follow, it throw exception:
```csharp
var httpClient = new FluentClient();
try
{
    var res = await new HttpClient().GetAsync(@"http://ezcardfile1.namex.cn/UploadFile/user/product/picture2101/328E09727F55A7876AF4731294706D80_2.jpg");
}
catch(Exception ex)
{

}
```

**Comment by Pathoschild** [comment]
The server is checking your `Accept` header, which doesn't match images by default. You can fix it by setting an `Accept` header that allows any response:
```cs
Stream data = await new FluentClient()
    .GetAsync(@"http://ezcardfile1.namex.cn/UploadFile/user/product/picture2101/328E09727F55A7876AF4731294706D80_2.jpg")
    .WithHeader("Accept", "*/*")
    .AsStream();

var image = Image.FromStream(data);
```
